In [28]:
#1
import numpy as np
x = np.random.random((5,5))
print('5x5 array with random values')
print(x)
print('\nfor minimum value')
print(x.min())
print('\nfor max value')
print(x.max())

5x5 array with random values
[[0.35305452 0.77308057 0.91116879 0.81083872 0.61126989]
 [0.12226376 0.18157432 0.78350166 0.08200443 0.03418223]
 [0.98053467 0.87096434 0.31430379 0.20248195 0.00216484]
 [0.56446226 0.84846511 0.78381235 0.15396438 0.28847722]
 [0.53921532 0.48113929 0.96097807 0.9115271  0.44093385]]

for minimum value
0.0021648436571473084

for max value
0.9805346663453022


In [29]:
#2
a = np.arange(10)
np.random.shuffle(a)
a

array([4, 2, 8, 9, 1, 7, 3, 0, 5, 6])

In [30]:
#3
x = np.random.rand(10,4)
print(x)
y = x[:5,:]
print('\n First five rows of an array')
print(y)

[[0.38781912 0.61745433 0.19954905 0.06047647]
 [0.89721472 0.79390224 0.34591878 0.47450112]
 [0.50717936 0.55646337 0.57368918 0.95776193]
 [0.47086132 0.18429001 0.9106628  0.86530564]
 [0.66080709 0.89440045 0.32288279 0.04800369]
 [0.14989192 0.38819703 0.06488709 0.35354185]
 [0.82771779 0.25921304 0.07246606 0.51989971]
 [0.35041448 0.47917394 0.44900032 0.86881399]
 [0.77652442 0.89777399 0.32220668 0.8005579 ]
 [0.35309751 0.83238402 0.86054823 0.79438856]]

 First five rows of an array
[[0.38781912 0.61745433 0.19954905 0.06047647]
 [0.89721472 0.79390224 0.34591878 0.47450112]
 [0.50717936 0.55646337 0.57368918 0.95776193]
 [0.47086132 0.18429001 0.9106628  0.86530564]
 [0.66080709 0.89440045 0.32288279 0.04800369]]


In [31]:
#4
x = np.random.randint(0,3,5)
print('FIRST ARRAY:')
print(x)
y = np.random.randint(0,3,5)
print('SECOND ARRAY')
print(y)
print('Above two arrays are equal or not')
array_equal = np.allclose(x,y)
print(array_equal)

FIRST ARRAY:
[1 1 1 0 2]
SECOND ARRAY
[1 0 1 1 1]
Above two arrays are equal or not
False


In [32]:
#5
def most_frequent(List):
  return max(set(List), key = List.count)
List = [6,9,5,1,7,5,1,0,1,5,5,0,8,9,0,7,0,7,6,5,1,1,9,5,3,8,7,9,6,3,4,5,9,7,2,7,0,2,2,6]
print(most_frequent(List))

5
